### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by antfu** [zxch3n/wenyanizer#1]
Hi there!

I am the author of [Wenyan for VSCode](https://github.com/antfu/wenyan-lang-vscode). Just saw your great work and I would love to integrate this into the extension. Wondering if you are interested in it.

Thanks!

**Comment by zxch3n** [comment]
Great! I love it. 

How can I help you?

**Comment by antfu** [comment]
Cool! Then I will make a try first. Will keep you update to date!

**Comment by antfu** [comment]
Hi! Do you have any js examples I can test with? Thanks

**Comment by zxch3n** [comment]
All the test cases are in `/test/jsTestCases`

**Comment by antfu** [comment]
Sorry I missed that.

I think I have made that:
![image](https://user-images.githubusercontent.com/11247099/71503497-64e05500-28b0-11ea-978a-782a9181f44d.png)

It's shipped in v0.10.0. You can try it out if you are using VSCode! 🎉

**Comment by zxch3n** [comment]
Amazing! I've added this to README

**Comment by antfu** [comment]
I have updated my README as well. Thanks again for your great work. If you got any issues using this feature, please feel free to tell me. Thanks!
